services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    ports:
      - 8888:8888
    volumes:
      - ./root_jupyter:/root/.jupyter
      - ./:/workspace
    networks:
      - default
      - shared-network
networks:
  shared-network:
    external: true
